// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oblong_Api.Data;

#nullable disable

namespace Oblong_Api.Migrations
{
    [DbContext(typeof(PersonalDbContext))]
    partial class PersonalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Oblong_Api.Models.SiteAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("IP")
                        .HasColumnType("longtext");

                    b.Property<string>("SiteName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TimeEntered")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TimeExited")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("site_access", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
